//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HideItWF.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IPhotographerService")]
    public interface IPhotographerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotographerService/GetPhotographerFirstName", ReplyAction="http://tempuri.org/IPhotographerService/GetPhotographerFirstNameResponse")]
        string GetPhotographerFirstName(string photographerUsername, string photogrpaherPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotographerService/GetPhotographerFirstName", ReplyAction="http://tempuri.org/IPhotographerService/GetPhotographerFirstNameResponse")]
        System.Threading.Tasks.Task<string> GetPhotographerFirstNameAsync(string photographerUsername, string photogrpaherPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotographerService/GetPhotographerLastName", ReplyAction="http://tempuri.org/IPhotographerService/GetPhotographerLastNameResponse")]
        string GetPhotographerLastName(string photographerUsername, string photogrpaherPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotographerService/GetPhotographerLastName", ReplyAction="http://tempuri.org/IPhotographerService/GetPhotographerLastNameResponse")]
        System.Threading.Tasks.Task<string> GetPhotographerLastNameAsync(string photographerUsername, string photogrpaherPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotographerService/GetPhotographerEmail", ReplyAction="http://tempuri.org/IPhotographerService/GetPhotographerEmailResponse")]
        string GetPhotographerEmail(string photographerUsername, string photogrpaherPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotographerService/GetPhotographerEmail", ReplyAction="http://tempuri.org/IPhotographerService/GetPhotographerEmailResponse")]
        System.Threading.Tasks.Task<string> GetPhotographerEmailAsync(string photographerUsername, string photogrpaherPassword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPhotographerServiceChannel : HideItWF.ServiceReference1.IPhotographerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PhotographerServiceClient : System.ServiceModel.ClientBase<HideItWF.ServiceReference1.IPhotographerService>, HideItWF.ServiceReference1.IPhotographerService {
        
        public PhotographerServiceClient() {
        }
        
        public PhotographerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PhotographerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhotographerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhotographerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetPhotographerFirstName(string photographerUsername, string photogrpaherPassword) {
            return base.Channel.GetPhotographerFirstName(photographerUsername, photogrpaherPassword);
        }
        
        public System.Threading.Tasks.Task<string> GetPhotographerFirstNameAsync(string photographerUsername, string photogrpaherPassword) {
            return base.Channel.GetPhotographerFirstNameAsync(photographerUsername, photogrpaherPassword);
        }
        
        public string GetPhotographerLastName(string photographerUsername, string photogrpaherPassword) {
            return base.Channel.GetPhotographerLastName(photographerUsername, photogrpaherPassword);
        }
        
        public System.Threading.Tasks.Task<string> GetPhotographerLastNameAsync(string photographerUsername, string photogrpaherPassword) {
            return base.Channel.GetPhotographerLastNameAsync(photographerUsername, photogrpaherPassword);
        }
        
        public string GetPhotographerEmail(string photographerUsername, string photogrpaherPassword) {
            return base.Channel.GetPhotographerEmail(photographerUsername, photogrpaherPassword);
        }
        
        public System.Threading.Tasks.Task<string> GetPhotographerEmailAsync(string photographerUsername, string photogrpaherPassword) {
            return base.Channel.GetPhotographerEmailAsync(photographerUsername, photogrpaherPassword);
        }
    }
}
