//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HideItWF.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IOhadWCFService")]
    public interface IOhadWCFService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOhadWCFService/GetMails", ReplyAction="http://tempuri.org/IOhadWCFService/GetMailsResponse")]
        string[] GetMails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOhadWCFService/GetMails", ReplyAction="http://tempuri.org/IOhadWCFService/GetMailsResponse")]
        System.Threading.Tasks.Task<string[]> GetMailsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOhadWCFServiceChannel : HideItWF.ServiceReference2.IOhadWCFService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OhadWCFServiceClient : System.ServiceModel.ClientBase<HideItWF.ServiceReference2.IOhadWCFService>, HideItWF.ServiceReference2.IOhadWCFService {
        
        public OhadWCFServiceClient() {
        }
        
        public OhadWCFServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OhadWCFServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OhadWCFServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OhadWCFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetMails() {
            return base.Channel.GetMails();
        }
        
        public System.Threading.Tasks.Task<string[]> GetMailsAsync() {
            return base.Channel.GetMailsAsync();
        }
    }
}
